### ISSUE TITLE
AttributeError: 'DatetimeColumn' object has no attribute 'str' running the covid-19 app

### ISSUE THREAD

**Issue by gmarkall** [rapidsai/plotly-dash-rapids-census-demo#4]
Having just followed the directions in the README on the covid-19 branch, after starting the app it's possible to browse to the server and see a page, but there's no map, and in the console I see various exceptions, of the form:

```

[2020-06-12 15:21:13,791] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/dash/dash.py", line 1459, in dispatch
    response.set_data(self.callback_map[output]["callback"](*args))
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/dash/dash.py", line 1339, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "app-covid.py", line 1188, in update_plots
    covid_data_loaded_latest_date = delayed(update_latest_update_covid)(client.get_dataset('pd_covid')).compute()
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/dask/base.py", line 444, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/distributed/client.py", line 2674, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/distributed/client.py", line 1974, in gather
    asynchronous=asynchronous,
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/distributed/client.py", line 824, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/distributed/client.py", line 1833, in _gather
    raise exception.with_traceback(traceback)
  File "app-covid.py", line 212, in load_covid
    df_county.Last_Update = pd.to_datetime(df_county.Last_Update.str.split(' ')[
  File "/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/cudf/core/series.py", line 1504, in str
    return self._column.str(parent=self)
AttributeError: 'DatetimeColumn' object has no attribute 'str'
```

I stopped the server with Ctrl+C and started it again, to get a slightly different message:

```
$ python app-covid.py 
Found dataset at ../data/census_data_minimized.parquet
Dask status: http://127.0.0.1:8787/status
loading latest covid dataset...
Running on http://0.0.0.0:8050/
Debugger PIN: 955-443-814
 * Serving Flask app "app-covid" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
loading cached latest covid dataset...
/home/gmarkall/miniconda3/envs/plotly_env/lib/python3.7/site-packages/cudf/core/column/string.py:1738: UserWarning:

`expand` parameter defatults to True.

distributed.worker - WARNING -  Compute Failed
Function:  load_covid
args:      ('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/%s.csv', '../data/acs2018_county_population.parquet')
kwargs:    {}
Exception: AttributeError("'DatetimeColumn' object has no attribute 'str'")
```

I'm not sure if there's something wrong with my setup or I've mis-followed some of the directions - is there anything I can do to try and narrow down what the problem is?

**Comment by AjayThorve** [comment]
I am assuming you are running it through a conda env, can you post the results of `conda list`?

**Comment by exactlyallan** [comment]
@AjayThorve Tried with latest env. Different error but I believe the JHU data format has probably changed causing errors.
